.TH "srcpac" "1" "March 04, 2005" "Jason Chu" ""
.SH "NAME"
srcpac \- A bash build wrapper for pacman.

.SH "SYNOPSIS"
\fBsrcpac\fR <operation> [options] [package] ...

.SH "DESCRIPTION"
\fBsrcpac\fR is a wrapper for pacman. It allows for automatic building of specified packages from source. The built package is then installed via pacman. If you never tell srcpac to build anything from source, it will act just like pacman.
.SH "OPERATIONS"
For additional OPERATIONS not specified below, see pacman manpage. Only those OPERATIONS specified below have been modified.

.TP
\fB\-R, \-\-remove\fR
Remove a package from the system. Works the same as \fBpacman\fR. In addition, the 'from\-source' marking will be removed.

.TP
\fB\-Q, \-\-query\fR
Query the package database. Works the same as \fBpacman\fR. Additionally, use of the \fB\-i\fR option tells you whether a package is marked as 'from\-source' or not.

.TP
\fB\-S, \-\-sync\fR
Synchronize packages. Works the same as \fBpacman\fR. Additional flags may be specified to build something from source (see below).

.TP
\fB\-h, \-\-help\fR
Display syntax for the given operation. If no operation was supplied then the general syntax is shown.
.SH "OPTIONS"
See pacman manpage. No additional general options beyond what pacman provides. See specific section below for added options specific to the operation.
.SH "SYNC OPTIONS"
For additional SYNC options not specified below, see pacman manpage. Only those options specified below have been modified.

.TP
\fB\-b, \-\-build\fR
.br
Build specified package from source. This runs \fBmakepkg\fR in /var/srcpac/<package>. This may build an older version of the package if the abs tree is not updated.

.TP
\fB\-bb\fR
.br
Build specified package and its dependencies from source. This runs \fBmakepkg\fR in /var/srcpac/<package>. This may build an older version of the packages if the abs tree is not updated.

.TP
\fB\-bbb\fR
.br
Build specified package, its dependencies and its makedependencies from source. This runs \fBmakepkg\fR in /var/srcpac/<package>. This may build an older version of the packages if the abs tree is not updated.

.TP
\fB\-m, \-\-makedeps\fR
.br
By default \fBsrcpac\fR keeps the makedependencies installed. With this option \fBsrcpac\fR will remove them after the build.

.TP
\fB\-o, \-\-onlyconf\fR
.br
Applies the sed command to a PKGBUILD (see CONFIGURATION), then pipes the output to less or the pager set in the PAGER environment variable. This allows you to make sure the changes are applied properly. No actual build occurs when using \fB\-o\fR.

.TP
\fB\-y, \-\-refresh\fR
.br
This command updates the abs tree and the pacman database.
.SH "QUERY OPTIONS"
For additional QUERY options not specified below, see pacman manpage. Only those options specified below have been modified.

.TP
\fB\-b, \-\-build\fR
.br
Shows all packages installed with fBsrcpac\fR.
.SH "REMOVE OPTIONS"
For additional QUERY options not specified below, see pacman manpage. Only those options specified below have been modified.

.TP
\fB\-b, \-\-build\fR
.br
With this option \fBsrcpac\fR will remove only the build-flag, but not the installed package.

.TP
\fB\-o, \-\-onlyconf\fR
.br
With this option \fBsrcpac\fR will remove only the patchfile, but not the installed package.
.SH "CONFIGURATION"
\fBsrcpac\fR lets you specify custom configs based on sed commands applied to PKGBUILDs. The config files are simple sed script files and have to be put in \fI/etc/srcpac.d/\fR. The config files have to be named like the packages they apply to. ie \fI/etc/srcpac.d/less\fR.

.TP
\fBExample\fI /etc/srcpac.d/less\fB:\fR

s#--prefix=/usr#--prefix=/usr/local#

.TP
The above example config is supplied to the PKGBUILD in a sed command like this:

sed \-f CONFIG PKGBUILD

.TP
Since writing these rules can be kind of tricky, it is best to use the \fB\-o\fR flag (see above) until you are sure things look right.

.SH "SEE ALSO"
.B pacman
is the Arch Linux package manager.
.SH "AUTHORS"
Jason Chu <jason@archlinux.org>
Andrea Scarpino <andrea@archlinux.org>

